version: '3'

services:
    redis:
        image: redis:alpine
        command: ["redis-server", "--bind", "redis", "--port", "6379"]
        ports:
            - 6379:6379
    nextjs: 
        build: ./
        ports:
            - 3000:3000
        depends_on:
            - redis

volumes:
    letsencrypt: